version: "3"
services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env} 
    environment:
      - NODE_ENV=production
    restart: always
