version: "3"
services:
  app:
    image: vivek6201/judge-ide-backend
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.6"
    build:
      context: .
      target: prod
    ports:
      - "4001:4001"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - NODE_ENV=production
    restart: always
