version: "3"
services:
  app:
    image: ide-backend
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules
    ports:
      - "4001:4001"
    env_file:
      - ${ENV_FILE:-.env} 
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Ensures file changes are detected
      - WATCHPACK_POLLING=true